# Generated by Django 5.0.14 on 2026-10-01 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_remove_rutina_ejercicios_rutina_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaEjercicioCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='rutinas.rutinaejercicio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rutinaejerciciocompletado',
            constraint=models.UniqueConstraint(fields=('item', 'fecha'), name='unico_completado_por_fecha'),
        ),
    ]
